### ISSUE TITLE
unset_builtin

### ISSUE THREAD

**Issue by ChewyToast** [Vkhrabrov/minishell_42#1]
Hi @Vkhrabrov and @ccg-v,

This minishell looks amazing!
I just wanted to point out a small detail, in the `unset_builtin` function I haven't seen any kind of validation, as far as I remember bash also validates the arguments in the `unset` command. Luckily they are the same conditions/validations as in `export`, so the function I think you validate with in export, `is_var_name_valid`, could be useful for unset.

In any case, I don't think this validation is done in the evaluation, but it is an interesting point, if only as a curiosity.

:)

**Comment by ccg-v** [comment]
Fixed, Bruno, our angel of light! Thank you very much for your supervision!
